name = "hx-houtiku-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 2 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "hx-houtiku"
database_id = "fd1c90d5-cf6a-45de-8d7d-90df10e611b6"

[durable_objects]
bindings = [
  { name = "MESSAGE_RELAY", class_name = "MessageRelay" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MessageRelay"]

[vars]
ENCRYPTION_CURVE = "secp256k1"

routes = [
  { pattern = "houtiku.api.woa.qzz.io", custom_domain = true }
]
